nginx:
    image: nginx
    ports:
        - "8181:80"
    volumes:
        - ./www:/usr/share/nginx/html
        - ./conf/nginx.conf:/nginx.conf
        - ./logs/nginx:/var/log/nginx
    links:
        - php:php
    command: nginx -c /nginx.conf

php:
    image: php:fpm
    ports:
        - "9000:9000"
    volumes:
        - ./www:/var/www/html
